language: go
sudo: false
notifications:
  email: false
go:
- 1.6.x
- 1.7.x
- 1.8.x
- 1.9.x
- master
before_script:
- go get gopkg.in/urfave/cli.v1
- go get github.com/c9s/goprocinfo/linux
- go get github.com/montanaflynn/stats
script:
- go test -v ./...
