package main

import (
	"fmt"
	"github.com/penberg/ustat"
	"gopkg.in/urfave/cli.v1"
	"os"
	"os/signal"
	"regexp"
	"strconv"
	"syscall"
	"time"
)

const defaultDelay = 1

func main() {
	app := cli.NewApp()
	app.Name = "ustat"
	app.Usage = "Unified system statistics collector"
	app.Authors = []cli.Author{
		cli.Author{
			Name:  "Pekka Enberg",
			Email: "penberg@iki.fi",
		},
	}
	app.HideHelp = true
	app.ArgsUsage = "[delay]"
	app.Flags = []cli.Flag{
		cli.BoolFlag{
			Name:  "c,cpu",
			Usage: "enable CPU stats collection",
		},
		cli.BoolFlag{
			Name:  "i,int",
			Usage: "enable interrupt stats collection",
		},
		cli.BoolFlag{
			Name:  "n,net",
			Usage: "enable network stats collection",
		},
		cli.BoolFlag{
			Name:  "d,disk",
			Usage: "enable disk stats collection",
		},
		cli.StringFlag{
			Name:  "o,output",
			Usage: "write output to `FILE`",
		},
		cli.StringFlag{
			Name:  "delimiter",
			Usage: "delimiter used in the output file",
			Value: "\t",
		},
		cli.StringFlag{
			Name:  "grep",
			Usage: "filter stats using an regular expression `PATTERN`",
		},
		cli.HelpFlag,
	}
	app.Action = func(ctx *cli.Context) error {
		var stats []*ustat.Stat
		if ctx.Bool("help") {
			cli.ShowAppHelp(ctx)
			return nil
		}
		if ctx.Bool("cpu") {
			stats = append(stats, ustat.NewCPUsStat())
		}
		if ctx.Bool("int") {
			stats = append(stats, ustat.NewInterruptsStat())
		}
		if ctx.Bool("net") {
			stats = append(stats, ustat.NewNetStat())
		}
		if ctx.Bool("disk") {
			stats = append(stats, ustat.NewDiskStat())
		}
		output := os.Stdout
		outputPath := ctx.String("output")
		if outputPath != "" {
			file, err := os.Create(outputPath)
			if err != nil {
				return cli.NewExitError(fmt.Sprintf("Unable to open file: %v", err), 2)
			}
			defer file.Close()
			output = file
		}
		pattern := ctx.String("grep")
		if len(stats) == 0 {
			stats = []*ustat.Stat{
				ustat.NewCPUsStat(),
				ustat.NewInterruptsStat(),
				ustat.NewNetStat(),
				ustat.NewDiskStat(),
			}
		}
		delimiter := ctx.String("delimiter")
		delay := defaultDelay
		args := ctx.Args()
		if len(args) > 0 {
			rawDelay := args[0]
			var err error
			delay, err = strconv.Atoi(rawDelay)
			if err != nil {
				return cli.NewExitError(fmt.Sprintf("Failed to parse delay argument: '%s'", rawDelay), 3)
			}

		}
		fmt.Fprintf(output, "# This file has been generated by ustat.\n")
		fmt.Fprintf(output, "#\n")
		fmt.Fprintf(output, "# Column descriptions:\n")
		for _, stat := range stats {
			for _, description := range stat.Descriptions {
				if pattern != "" {
					matched, err := regexp.MatchString(pattern, description)
					if err != nil || !matched {
						continue
					}
				}
				fmt.Fprintf(output, "# %s\n", description)
			}
		}
		for statIdx, stat := range stats {
			for nameIdx, name := range stat.Names {
				if pattern != "" {
					matched, err := regexp.MatchString(pattern, name)
					if err != nil || !matched {
						continue
					}
				}
				if statIdx+nameIdx == 0 {
					fmt.Fprintf(output, "%s", name)
				} else {
					fmt.Fprintf(output, "%s%s", delimiter, name)
				}
			}
		}
		fmt.Fprintln(output, "")
		sigs := make(chan os.Signal, 1)
		done := make(chan bool, 1)
		signal.Notify(sigs, syscall.SIGINT, syscall.SIGTERM)
		go func() {
			sig := <-sigs
			fmt.Println()
			fmt.Println(sig)
			done <- true
		}()
		ticker := time.NewTicker(time.Duration(delay) * time.Second)
		go func() {
			for _ = range ticker.C {
				for statIdx, stat := range stats {
					values := stat.Collector.Collect()
					for valueIdx, value := range values {
						if pattern != "" {
							matched, err := regexp.MatchString(pattern, stat.Names[valueIdx])
							if err != nil || !matched {
								continue
							}
						}
						if statIdx+valueIdx == 0 {
							fmt.Fprintf(output, "%d", value)
						} else {
							fmt.Fprintf(output, "%s%d", delimiter, value)
						}
					}
				}
				fmt.Fprintln(output, "")
			}
		}()
		<-done

		return nil
	}
	app.Run(os.Args)
}
